name: Integracao continua com github actions

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: login no docker hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build book jar
        working-directory: ./book
        run: mvn clean package -DskipTests
      - name: docker compose build 
        working-directory: .
        run: docker compose build
      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/book:latest ${{ secrets.DOCKER_USERNAME }}/book:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/book:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/book:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Deploy naming-server
          run: |
            docker pull rodrigodocker158/naming-server:latest
            docker rm -f naming-server || true
            docker run -d -p 8761:8761 --name naming-server rodrigodocker158/naming-server:latest

        - name: Deploy api-gateway
          run: |
            docker pull rodrigodocker158/api-gateway:latest
            docker rm -f api-gateway || true
            docker run -d -p 8765:8765 \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --name api-gateway \
              rodrigodocker158/api-gateway:latest

        - name: Deploy livro-db
          run: |
            docker pull postgres:13
            docker rm -f livro-db || true
            docker run -d \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e POSTGRES_DB=livro \
              --name livro-db \
              -v livro-db-data:/var/lib/postgresql/data \
              postgres:13

        - name: Deploy book
          run: |
            docker pull rodrigodocker158/book:latest
            docker rm -f book || true
            docker run -d -p 8000:8000 \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://livro-db:5432/livro \
              -e SPRING_DATASOURCE_USERNAME=postgres \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka \
              --name book \
              rodrigodocker158/book:latest
